# Generated by Django 6.0 on 2025-12-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('TAX', 'Taxi'), ('MIU', 'Microbus urbano'), ('CIT', 'Camioneta intermunicipal'), ('MIT', 'Microbus intermunicipal')], default='TAX', max_length=3)),
                ('precio', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=20)),
                ('capacidad', models.CharField(max_length=2)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
