# Generated by Django 6.0 on 2026-01-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cosol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
    ]
