# Generated by Django 6.0 on 2026-01-06 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cosol', '0002_vehiculos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vehiculos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Imagen', to='admin_cosol.vehiculos')),
            ],
        ),
    ]
