# Generated by Django 6.0 on 2026-01-06 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cosol', '0003_imagenvehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='imagen',
        ),
    ]
