# Generated by Django 6.0 on 2026-01-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cosol', '0004_remove_vehiculos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('Taxi', 'Taxi'), ('Microbus Urbano', 'Microbus urbano'), ('Camioneta intermunicipal', 'Camioneta intermunicipal'), ('Microbus intermunicipal', 'Microbus intermunicipal')], default='TAX', max_length=50),
        ),
    ]
