# Generated by Django 6.0 on 2026-02-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cosol', '0005_alter_vehiculos_tipo_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
    ]
