# Generated by Django 6.0 on 2026-02-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cosol', '0006_vehiculos_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenVehiculo',
        ),
    ]
