# Generated by Django 6.0 on 2026-03-02 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cosol', '0007_delete_imagenvehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interno', models.IntegerField(max_length=3)),
                ('placa', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.IntegerField(max_length=4)),
                ('radio', models.CharField(max_length=20)),
                ('marca_radio', models.CharField(max_length=20)),
                ('soat', models.DateField(blank=True, null=True)),
                ('tecnomicanica', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('rh', models.CharField(max_length=3)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('eps', models.CharField(max_length=50)),
                ('arl', models.CharField(max_length=50)),
                ('anotaciones', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='conductores/')),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_cosol.taxis')),
            ],
        ),
    ]
