# Generated by Django 6.0 on 2026-03-11 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cosol', '0008_taxis_conductores'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaControls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=10)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('refrendada1', models.DateField(blank=True, null=True, verbose_name='Refrendada 1')),
                ('vencimientorefrendada1', models.DateField(blank=True, null=True, verbose_name='vencimiento refrendad 1')),
                ('refrendada2', models.DateField(blank=True, null=True, verbose_name='Refrendada 2')),
                ('vencimientorefrendada2', models.DateField(blank=True, null=True, verbose_name='vencimiento refrendada 2')),
                ('refrendada3', models.DateField(blank=True, null=True, verbose_name='Refrendada 3')),
                ('vencimientorefrendada3', models.DateField(blank=True, null=True, verbose_name='vencimiento refrendada 3')),
                ('refrendada4', models.DateField(blank=True, null=True, verbose_name='Refrendada 4')),
                ('vencimientorefrendada4', models.DateField(blank=True, null=True, verbose_name='vencimiento refrendada 4')),
                ('refrendada5', models.DateField(blank=True, null=True, verbose_name='Refrendada 5')),
                ('vencimientorefrendada5', models.DateField(blank=True, null=True, verbose_name='vencimiento refrendada 5')),
                ('refrendada6', models.DateField(blank=True, null=True, verbose_name='Refrendada 6')),
                ('vencimientorefrendada6', models.DateField(blank=True, null=True, verbose_name='vencimiento refrendada 6')),
                ('refrendada7', models.DateField(blank=True, null=True, verbose_name='Refrendada 7')),
                ('vencimientorefrendada7', models.DateField(blank=True, null=True, verbose_name='vencimiento refrendada 7')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_cosol.conductores')),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_cosol.taxis')),
            ],
        ),
    ]
